<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.4%20np_array_creation_routines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_array_creation_routines.htm
import numpy as np

In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.empty.html
#numpy.empty(shape, dtype=float, order='C', *, like=None)
x = np.empty([3,2], dtype = np.int8)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[[-124    5]
 [ -78  -92]
 [-122   90]]
(3, 2)
2
int8
1


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
#numpy.zeros(shape, dtype=float, order='C', *, like=None)
x = np.zeros(5)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[0. 0. 0. 0. 0.]
(5,)
1
float64
8


In [ ]:
x = np.zeros((5,), dtype = np.int64)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[0 0 0 0 0]
(5,)
1
int64
8


In [ ]:
x = np.zeros((5,), dtype = np.uint8)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[0 0 0 0 0]
(5,)
1
uint8
1


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.ones.html
#numpy.ones(shape, dtype=None, order='C', *, like=None)
x = np.ones(5)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[1. 1. 1. 1. 1.]
(5,)
1
float64
8


In [ ]:
x = np.ones(5, dtype = np.int64)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[1 1 1 1 1]
(5,)
1
int64
8


In [ ]:
x = np.ones(5, dtype = np.uint8)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.itemsize)

[1 1 1 1 1]
(5,)
1
uint8
1
