<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.8%20np_advanced_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
y = x[[0,1,2], [0,1,0]]
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [ ]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
print(x)
rows = np.array([[0,0],[3,3]])
print(rows)
cols = np.array([[0,2],[0,2]])
print(cols)
y = x[rows,cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]


In [ ]:
z = x[1:4,1:3]
print(z)

[[ 4  5]
 [ 7  8]
 [10 11]]


In [ ]:
y = x[1:4,[1,2]]
print(y)

[[ 4  5]
 [ 7  8]
 [10 11]]


In [ ]:
x > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
print(x[x > 5])

[ 6  7  8  9 10 11]


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.isnan.html
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a)
print(a[np.isnan(a)])

[nan  1.  2. nan  3.  4.  5.]
[nan nan]


In [ ]:
print(a)
print(a[~np.isnan(a)])

[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.iscomplex.html
a = np.array([1, 2.1+6j, 5, 3.5+5j])
print(a)
print(a.dtype)
print(a[np.iscomplex(a)])

[1. +0.j 2.1+6.j 5. +0.j 3.5+5.j]
complex128
[2.1+6.j 3.5+5.j]


In [ ]:
print(a)
print(a[~np.iscomplex(a)])

[1. +0.j 2.1+6.j 5. +0.j 3.5+5.j]
[1.+0.j 5.+0.j]
