<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.6%20np_array_from_numerical_ranges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_array_from_numerical_ranges.htm
import numpy as np
x = np.arange(5)
print(x)
print(x.dtype)

[0 1 2 3 4]
int64


In [ ]:
x = np.arange(5, dtype = np.float32)
print(x)
print(x.dtype)

[0. 1. 2. 3. 4.]
float32


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.arange.html
#numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.linspace.html
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [ ]:
x = np.linspace(10,20, 5, endpoint = False)
print(x)

[10. 12. 14. 16. 18.]


In [ ]:
x = np.linspace(1,2,5, retstep = True)
print(x)
print(x[0])
print(x[1])

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
[1.   1.25 1.5  1.75 2.  ]
0.25


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.logspace.html
#numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
a = np.logspace(1.0, 2.0, num = 10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [ ]:
a = np.logspace(1,10,num = 10, base = 2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
