<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.19%20np_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_linear_algebra.htm
import numpy as np
#https://www.tutorialspoint.com/numpy/numpy_dot.htm
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[11,12],[13,14]])
print(b)
np.dot(a,b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


array([[37, 40],
       [85, 92]])

In [ ]:
a.dot(b)

array([[37, 40],
       [85, 92]])

In [ ]:
np.dot(b,a)

array([[47, 70],
       [55, 82]])

In [ ]:
b.dot(a)

array([[47, 70],
       [55, 82]])

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
a.dot(b), np.cross(a,b)

(11, array(-2))

In [ ]:
b.dot(a), np.cross(b,a)

(11, array(2))

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_vdot.htm
print(np.vdot(a,b))
print(np.vdot(b,a))

11
11


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_inner.htm
a = np.array([1,2,3])
print(a)
b = np.array([0,1,0])
print(b)
np.inner(a,b)

[1 2 3]
[0 1 0]


2

In [ ]:
np.inner(b,a)

2

In [ ]:
a = np.array([[1,2], [3,4]])
print(a)
b = np.array([[11, 12], [13, 14]])
print(b)
np.inner(a,b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


array([[35, 41],
       [81, 95]])

In [ ]:
np.inner(b,a)

array([[35, 81],
       [41, 95]])

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_matmul.htm
a = [[1,0],[0,1]]
print(a)
b = [[4,1],[2,2]]
print(b)
print(np.matmul(a,b))

[[1, 0], [0, 1]]
[[4, 1], [2, 2]]
[[4 1]
 [2 2]]


In [ ]:
print(np.matmul(b,a))

[[4 1]
 [2 2]]


In [ ]:
a = [[1,0],[0,1]]
print(a)
b = [1,2]
print(b)
print(np.matmul(a,b))
print(np.matmul(b,a))

[[1, 0], [0, 1]]
[1, 2]
[1 2]
[1 2]


In [ ]:
a = np.arange(8).reshape(2,2,2)
print(a)
b = np.arange(4).reshape(2,2)
print(b)
print(np.matmul(a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [ ]:
print(np.matmul(b,a))

[[[ 2  3]
  [ 6 11]]

 [[ 6  7]
  [26 31]]]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_determinant.htm
a = np.array([[1,2], [3,4]])
print(a)
print(np.linalg.det(a))

[[1 2]
 [3 4]]
-2.0000000000000004


In [ ]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]])
print(b)
print(np.linalg.det(b))
print(6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_solve.htm
#a + 2b = 1
#3a + 5b = 2
A = np.array([[1, 2], [3, 5]])
print(A)
b = np.array([1, 2])
print(b)
#Ax = b
x = np.linalg.solve(A, b)
print(x)
#x = inv(A)*b
ainv = np.linalg.inv(A)
print(ainv)
x = np.dot(ainv,b)
print(x)

[[1 2]
 [3 5]]
[1 2]
[-1.  1.]
[[-5.  2.]
 [ 3. -1.]]
[-1.  1.]


In [ ]:
#x + y + z = 6
#2y + 5z = -4
#2x + 5y - z = 27
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
print(A)
b = np.array([6,-4,27])
print(b)
#Ax = b
x = np.linalg.solve(A, b)
print(x)
#x = inv(A)*b
ainv = np.linalg.inv(A)
print(ainv)
x = np.dot(ainv,b)
print(x)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[ 6 -4 27]
[ 5.  3. -2.]
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
[ 5.  3. -2.]


In [ ]:
#x + y + z = 2
#6x - 4y + 5z = 31
#5x + 2y + 2z = 13
a = np.array([[1,1,1],[6,-4,5],[5,2,2]])
print(a)
b = np.array([2,31,13])
print(b)
#ax = b
x = np.linalg.solve(a, b)
print(x)
#x = inv(a)*b
ainv = np.linalg.inv(a)
print(ainv)
x = np.dot(ainv,b)
print(x)

[[ 1  1  1]
 [ 6 -4  5]
 [ 5  2  2]]
[ 2 31 13]
[ 3. -2.  1.]
[[-0.66666667  0.          0.33333333]
 [ 0.48148148 -0.11111111  0.03703704]
 [ 1.18518519  0.11111111 -0.37037037]]
[ 3. -2.  1.]


In [ ]:
#3x + y -2z = 7
#x - 3y + 4z = 15
#2x - 2y + z = 12
a = np.array([[3,1,-2],[1,-3,4],[2,-2,1]])
print(a)
b = np.array([7,15,12])
print(b)
x = np.linalg.solve(a, b)
print(x)
ainv = np.linalg.inv(a)
print(ainv)
x = np.dot(ainv,b)
print(x)

[[ 3  1 -2]
 [ 1 -3  4]
 [ 2 -2  1]]
[ 7 15 12]
[ 4. -1.  2.]
[[ 0.35714286  0.21428571 -0.14285714]
 [ 0.5         0.5        -1.        ]
 [ 0.28571429  0.57142857 -0.71428571]]
[ 4. -1.  2.]
