<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.18%20np_copies_and_views.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_copies_and_views.htm
import numpy as np
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
id(a)

140023776077712

In [ ]:
b = a
b

array([0, 1, 2, 3, 4, 5])

In [ ]:
id(b)

140023776077712

In [ ]:
b.shape = 3,2
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a.shape

(3, 2)

In [ ]:
b = a.view()
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
id(a)

140023761357680

In [ ]:
id(b)

140023761358352

In [ ]:
b.shape = 2,3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a = np.array([[10,10], [2,3], [4,5]])
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
s = a[:, :2]
s

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
id(a)

140023761360176

In [ ]:
id(s)

140023761359024

In [ ]:
a = np.array([[10,10], [2,3], [4,5]])
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
b = a.copy()
b

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
id(a)

140023761360752

In [ ]:
id(b)

140023761361136

In [ ]:
print(b is a)

False


In [ ]:
b[0,0] = 100
b

array([[100,  10],
       [  2,   3],
       [  4,   5]])

In [ ]:
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
c = a
c

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
id(a), id(c)

(140023761360752, 140023761360752)

In [ ]:
print(c is a)

True


In [ ]:
d = a.view()
d

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [ ]:
id(a), id(d)

(140023761360752, 140023761361712)

In [ ]:
print(d is a)

False
