<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.16%20np_sort_search_counting_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_sort_search_counting_functions.htm
import numpy as np
a = np.array([[3,7],[9,1]])
a

array([[3, 7],
       [9, 1]])

In [ ]:
np.sort(a) #sort row by row

array([[3, 7],
       [1, 9]])

In [ ]:
np.sort(a, axis = 0) #sort col by col

array([[3, 1],
       [9, 7]])

In [ ]:
np.sort(a.flatten())

array([1, 3, 7, 9])

In [ ]:
dt = np.dtype([('name', 'S10'),('age', int)])
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt)
a

array([(b'raju', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i8')])

In [ ]:
np.sort(a, order = 'name')

array([(b'amar', 27), (b'anil', 25), (b'raju', 21), (b'ravi', 17)],
      dtype=[('name', 'S10'), ('age', '<i8')])

In [ ]:
x = np.array([3, 1, 2])
x

array([3, 1, 2])

In [ ]:
#numpy.argsort(a, axis=- 1, kind=None, order=None)
y = np.argsort(x)
y

array([1, 2, 0])

In [ ]:
x[y]

array([1, 2, 3])

In [ ]:
for i in y:
   print(x[i])

1
2
3


In [ ]:
[x[i] for i in y]

[1, 2, 3]

In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.lexsort.html
nm = ('raju','anil','ravi','amar')
dv = ('f.y.', 's.y.', 's.y.', 'f.y.')
ind = np.lexsort((dv,nm)) # Sort by nm, then by dv
ind

array([3, 1, 0, 2])

In [ ]:
[dv[i] for i in ind]

['f.y.', 's.y.', 'f.y.', 's.y.']

In [ ]:
[nm[i] + ", " + dv[i] for i in ind]

['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']

In [ ]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [ ]:
np.argmax(a)

7

In [ ]:
a.flatten()

array([30, 40, 70, 80, 20, 10, 50, 90, 60])

In [ ]:
maxindex = np.argmax(a, axis = 0) #column wise
maxindex

array([1, 2, 0])

In [ ]:
maxindex = np.argmax(a, axis = 1) #row wise
maxindex

array([2, 0, 1])

In [ ]:
minindex = np.argmin(a)
minindex

5

In [ ]:
a.flatten()

array([30, 40, 70, 80, 20, 10, 50, 90, 60])

In [ ]:
a.flatten()[minindex]

10

In [ ]:
minindex = np.argmin(a, axis = 0) #column wise
minindex

array([0, 1, 1])

In [ ]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [ ]:
a[0,0]

30

In [ ]:
a[1,1]

20

In [ ]:
a[1,2]

10

In [ ]:
minindex = np.argmin(a, axis = 1) #row wise
minindex

array([0, 2, 0])

In [ ]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [ ]:
a[0,0]

30

In [ ]:
a[1,2]

10

In [ ]:
a[2,0]

50

In [ ]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]])
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [ ]:
np.nonzero(a)

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))

In [ ]:
a > 0

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False,  True]])

In [ ]:
a[a>0]

array([30, 40, 20, 10, 50, 60])

In [ ]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
y = np.where(x > 3)
y

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [ ]:
x[y]

array([4., 5., 6., 7., 8.])

In [ ]:
x[x>3]

array([4., 5., 6., 7., 8.])

In [ ]:
x = np.arange(9.).reshape(3, 3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
condition = np.mod(x,2) == 0
condition

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [ ]:
np.extract(condition, x)

array([0., 2., 4., 6., 8.])

In [ ]:
x[np.mod(x,2) == 0]

array([0., 2., 4., 6., 8.])

In [ ]:
x[x%2 == 0]

array([0., 2., 4., 6., 8.])