<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.5%20np_array_from_existing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_array_from_existing_data.htm
import numpy as np
x = [1,2,3]
print(x)
a = np.asarray(x)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1, 2, 3]
[1 2 3]
(3,)
1
int64


In [ ]:
a = np.asarray(x, dtype = np.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1. 2. 3.]
(3,)
1
float32


In [ ]:
x = (1,2,3)
print(x)
a = np.asarray(x)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

(1, 2, 3)
[1 2 3]
(3,)
1
int64


In [ ]:
a = np.asarray(x, dtype = np.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1. 2. 3.]
(3,)
1
float32


In [ ]:
x = [(1,2,3),(4,5)]
print(x)
a = np.asarray(x)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[(1, 2, 3), (4, 5)]
[(1, 2, 3) (4, 5)]
(2,)
1
object


<ipython-input-5-d054128d22d2>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.asarray(x)


In [ ]:
a = np.asarray(x, dtype = np.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

ValueError: ignored

In [ ]:
s = b'Hello World'
a = np.frombuffer(s, dtype = 'S1')
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
(11,)
1
|S1


In [ ]:
mylist = range(5)
print(mylist)
print(list(mylist))
list(mylist)

range(0, 5)
[0, 1, 2, 3, 4]


[0, 1, 2, 3, 4]

In [ ]:
mylist = range(5)
list(mylist)

[0, 1, 2, 3, 4]

In [ ]:
it = iter(mylist)
print(it)

In [ ]:
it = iter(mylist)
print(it)
x = np.fromiter(it, dtype = np.float32)
print(x)

[0. 1. 2. 3. 4.]
