<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.7%20np_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm
import numpy as np
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(s)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]


In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b = a[2:7:2]
print(b)

[2 4 6]


In [ ]:
b = a[5]
print(b)

5


In [ ]:
print(a[2:])

[2 3 4 5 6 7 8 9]


In [ ]:
print(a[2:5])

[2 3 4]


In [ ]:
a = np.arange(10,100,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
a[5:100:5]

array([35, 60, 85])

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1 2 3]
 [3 4 5]
 [4 5 6]]
(3, 3)
2
int64


In [ ]:
print(a[...,1])

[2 4 5]


In [ ]:
print(a[1,...])

[3 4 5]


In [ ]:
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]
