<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.9%20np_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm
import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
print(a)
print(a.shape)
print(a.ndim)
b = np.array([1.0,2.0,3.0])
print(b)
print(a+b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
(4, 3)
2
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
print(a)
print(a.shape)
print(a.ndim)
b = np.array([[1.0,2.0,3.0], [4.0,5.0,6.0]])
print(b)
print(a+b)


[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
(4, 3)
2
[[1. 2. 3.]
 [4. 5. 6.]]


ValueError: ignored

In [ ]:
A = np.array([[4, -1, 3],[7, 0, -2]])
A

array([[ 4, -1,  3],
       [ 7,  0, -2]])

In [ ]:
B = np.array([[-4, 2, 2], [-1, 5, 6]])
B

array([[-4,  2,  2],
       [-1,  5,  6]])

In [ ]:
A + B

array([[0, 1, 5],
       [6, 5, 4]])

In [ ]:
A*B

array([[-16,  -2,   6],
       [ -7,   0, -12]])

In [ ]:
2*A + 3*B

array([[-4,  4, 12],
       [11, 15, 14]])