<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.1%20np_ndarray_object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_ndarray_object.htm
import numpy as np

In [ ]:
mylist = [1,2,3]
print(mylist)

[1, 2, 3]


In [ ]:
#https://discuss.boardinfinity.com/t/what-are-tensors/19073
a = np.array(mylist)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1 2 3]
(3,)
1
int64


In [ ]:
mylist = [[1, 2], [3, 4]]
print(mylist)
a = np.array(mylist)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
(2, 2)
2
int64


In [ ]:
mylist = [1, 2, 3,4,5]
print(mylist)
a = np.array(mylist, ndmin = 2)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1, 2, 3, 4, 5]
[[1 2 3 4 5]]
(1, 5)
2
int64


In [ ]:
mylist = [1., 2., 3.,4.,5.]
print(mylist)
a = np.array(mylist, ndmin = 2)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1.0, 2.0, 3.0, 4.0, 5.0]
[[1. 2. 3. 4. 5.]]
(1, 5)
2
float64


In [ ]:
mylist = [1, 2, 3]
print(mylist)
a = np.array(mylist, dtype = complex)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[1, 2, 3]
[1.+0.j 2.+0.j 3.+0.j]
(3,)
1
complex128
