<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.14%20np_arithmetic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_arithmetic_operations.htm
import numpy as np
a = np.arange(9, dtype = np.float_).reshape(3,3)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
b = np.array([10,10,10])
b

array([10, 10, 10])

In [ ]:
np.add(a,b), a+b

(array([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]),
 array([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]))

In [ ]:
np.subtract(a,b), a-b

(array([[-10.,  -9.,  -8.],
        [ -7.,  -6.,  -5.],
        [ -4.,  -3.,  -2.]]),
 array([[-10.,  -9.,  -8.],
        [ -7.,  -6.,  -5.],
        [ -4.,  -3.,  -2.]]))

In [ ]:
np.multiply(a,b), a*b

(array([[ 0., 10., 20.],
        [30., 40., 50.],
        [60., 70., 80.]]),
 array([[ 0., 10., 20.],
        [30., 40., 50.],
        [60., 70., 80.]]))

In [ ]:
np.divide(a,b), a/b

(array([[0. , 0.1, 0.2],
        [0.3, 0.4, 0.5],
        [0.6, 0.7, 0.8]]),
 array([[0. , 0.1, 0.2],
        [0.3, 0.4, 0.5],
        [0.6, 0.7, 0.8]]))

In [ ]:
a = np.array([0.25, 1.33, 1, 0, 100])
a

array([  0.25,   1.33,   1.  ,   0.  , 100.  ])

In [ ]:
np.reciprocal(a)

<ipython-input-8-8988e9a787cf>:1: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(a)


array([4.       , 0.7518797, 1.       ,       inf, 0.01     ])

In [ ]:
b = np.array([100], dtype = int)
b

array([100])

In [ ]:
np.reciprocal(b)

array([0])

In [ ]:
a = np.array([10,100,1000])
a

array([  10,  100, 1000])

In [ ]:
np.power(a,2), a**2

(array([    100,   10000, 1000000]), array([    100,   10000, 1000000]))

In [ ]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [ ]:
np.power(a,b), a**b

(array([        10,      10000, 1000000000]),
 array([        10,      10000, 1000000000]))

In [ ]:
a = np.array([10,20,30])
a

array([10, 20, 30])

In [ ]:
b = np.array([3,5,7])
b

array([3, 5, 7])

In [ ]:
np.mod(a,b), a%b

(array([1, 0, 2]), array([1, 0, 2]))

In [ ]:
np.remainder(a,b)

array([1, 0, 2])

In [ ]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j])
a

array([-0.-5.6j,  0.+0.2j, 11.+0.j ,  1.+1.j ])

In [ ]:
np.real(a)

array([-0.,  0., 11.,  1.])

In [ ]:
np.imag(a)

array([-5.6,  0.2,  0. ,  1. ])

In [ ]:
np.conj(a)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

In [ ]:
np.angle(a)

array([-1.57079633,  1.57079633,  0.        ,  0.78539816])

In [ ]:
np.angle(a, deg = True)

array([-90.,  90.,   0.,  45.])

In [ ]:
range(9)

range(0, 9)

In [ ]:
for i in range(9):
  print(i)

0
1
2
3
4
5
6
7
8


In [ ]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array(range(9))
a.shape

(9,)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]