<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.10%20np_iterating_over_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_iterating_over_array.htm
import numpy as np
a = np.arange(0,60,5)
print(a)
print(a.ndim)
a = a.reshape(3,4)
print(a)
print(a.ndim)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
1
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
2


In [ ]:
for x in np.nditer(a):
   print(x, end=' ')

0 5 10 15 20 25 30 35 40 45 50 55 

In [ ]:
for x in a:
  print(x, end=' ')

[ 0  5 10 15] [20 25 30 35] [40 45 50 55] 

In [ ]:
b = a.T
print(b)
print(b.shape)
print(b.ndim)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
(4, 3)
2


In [ ]:
c = b.copy(order = 'C')
print(c)
print(c.shape)
for x in np.nditer(c):
   print(x, end=' ')

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
(4, 3)
0 20 40 5 25 45 10 30 50 15 35 55 

In [ ]:
c = b.copy(order = 'F')
print(c)
print(c.shape)
for x in np.nditer(c):
   print(x, end=' ')

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
(4, 3)
0 5 10 15 20 25 30 35 40 45 50 55 

In [ ]:
a = np.arange(0,60,5).reshape(3,4)
print(a)
print(a.shape)
for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x

print(a)
print(a.shape)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
(3, 4)
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
(3, 4)


In [ ]:
a = np.arange(0,60,5).reshape(3,4)
print(a)
print(a.shape)
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print(x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
(3, 4)
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] 

In [ ]:
b = np.array([1, 2, 3, 4], dtype = int)
print(b)

[1 2 3 4]


In [ ]:
print(a)
print(b)
for x,y in np.nditer([a,b]):
   print("%d:%d" % (x,y), end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[1 2 3 4]
0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

In [ ]:
a+b

array([[ 1,  7, 13, 19],
       [21, 27, 33, 39],
       [41, 47, 53, 59]])