<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.13%20np_mathematical_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_mathematical_functions.htm
import numpy as np
a = np.array([0,30,45,60,90])
a.shape

(5,)

In [ ]:
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
print(np.sin(np.deg2rad(a)))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
np.sqrt(1/2)

0.7071067811865476

In [ ]:
np.sqrt(1/5)

0.4472135954999579

In [ ]:
print(np.cos(a*np.pi/180))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [ ]:
print(np.tan(a*np.pi/180))

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
sin = np.sin(a*np.pi/180)
sin

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
inv = np.arcsin(sin)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.degrees(inv), np.rad2deg(inv)

(array([ 0., 30., 45., 60., 90.]), array([ 0., 30., 45., 60., 90.]))

In [ ]:
cos = np.cos(a*np.pi/180)
cos

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
inv = np.arccos(cos)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.degrees(inv), np.rad2deg(inv)

(array([ 0., 30., 45., 60., 90.]), array([ 0., 30., 45., 60., 90.]))

In [ ]:
tan = np.tan(a*np.pi/180)
tan

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [ ]:
inv = np.arctan(tan)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.degrees(inv), np.rad2deg(inv)

(array([ 0., 30., 45., 60., 90.]), array([ 0., 30., 45., 60., 90.]))

In [ ]:
a = np.array([1.0,5.55, 123, 0.567, 25.532])
a

array([  1.   ,   5.55 , 123.   ,   0.567,  25.532])

In [ ]:
np.around(a)

array([  1.,   6., 123.,   1.,  26.])

In [ ]:
np.around(a, decimals = 1)

array([  1. ,   5.6, 123. ,   0.6,  25.5])

In [ ]:
np.around(a, decimals = -1)

array([  0.,  10., 120.,   0.,  30.])

In [ ]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
a

array([-1.7,  1.5, -0.2,  0.6, 10. ])

In [ ]:
np.floor(a)

array([-2.,  1., -1.,  0., 10.])

In [ ]:
np.ceil(a)

array([-1.,  2., -0.,  1., 10.])

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
m = np.array(matrix)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matrix = [[1,2,3],[4,5,6]]
matrix

[[1, 2, 3], [4, 5, 6]]

In [ ]:
m = np.array(matrix)
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.array([1,1]) + np.array([2,3])

array([3, 4])