<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.11np_array_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_array_manipulation.htm
#https://www.tutorialspoint.com/numpy/numpy_reshape.htm
import numpy as np
#numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
a = np.arange(8)
print(a)
print(a.shape)
print(a.ndim)
b = a.reshape(4,2)
print(b)
print(b.shape)
print(b.ndim)

[0 1 2 3 4 5 6 7]
(8,)
1
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
2


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_ndarray_flat.htm
a = np.arange(8).reshape(2,4)
print(a)
print(a.shape)
print(a.ndim)
print(a[1,1])
#'After applying the flat function:'
print(a.flat[5])

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
2
5
5


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_ndarray_flatten.htm
a = np.arange(8).reshape(2,4)
print(a)
print(a.shape)
print(a.flatten())
print(a.flatten(order = 'F'))

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_ndarray_ravel.htm
a = np.arange(8).reshape(2,4)
print(a)
print(a.shape)
print(a.ravel())
print(a.ravel(order = 'F'))

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_transpose.htm
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_ndarray_t.htm
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_rollaxis.htm
#https://numpy.org/doc/stable/reference/generated/numpy.rollaxis.html
#numpy.rollaxis(a, axis, start=0)
a = np.arange(8).reshape(2,2,2)
print(a)
print(a.shape)
print(a.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)
3


In [ ]:
print(np.rollaxis(a,2))

[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [ ]:
print(np.rollaxis(a,2,1))

[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [ ]:
a = np.arange(8).reshape(2,4)
print(a)
print(np.rollaxis(a,0))
print(np.rollaxis(a,1))

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [ ]:
a = np.ones((3,4,5,6))
print(a)
print(np.rollaxis(a, 3, 1))
print(a.shape)
print(np.rollaxis(a, 3, 1).shape)

[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1

In [ ]:
print(a.shape)
print(np.rollaxis(a, 2).shape)

(3, 4, 5, 6)
(5, 3, 4, 6)


In [ ]:
print(a.shape)
print(np.rollaxis(a, 1, 4).shape)

(3, 4, 5, 6)
(3, 5, 6, 4)


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_swapaxes.htm
#https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html
a = np.arange(8).reshape(2,2,2)
print(a)
print(np.swapaxes(a, 2, 0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [ ]:
a = np.arange(8).reshape(2,4)
print(a)
print(np.swapaxes(a, 1, 0))
print(np.swapaxes(a, 0, 1))

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_broadcast.htm
x = np.array([[1], [2], [3]])
print(x.ndim)
x.shape

2


(3, 1)

In [ ]:
y = np.array([4, 5, 6])
print(y.ndim)
y.shape

1


(3,)

In [ ]:
# tobroadcast x against y
b = np.broadcast(x,y)
print(b.shape)
out = np.zeros(b.shape)
print(out)
out.flat = [u+v for (u,v) in b]
out

(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [ ]:
b = np.broadcast(x,y)
print(b.shape)
print(b)
for (u,v) in b:
  print(u,v)

(3, 3)
1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6


In [ ]:
b = np.broadcast(x,y)
print(b.shape)
[(u,v) for (u,v) in b]

(3, 3)


[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]

In [ ]:
# tobroadcast y against x
b = np.broadcast(y,x)
print(b.shape)
out = np.ones(b.shape)
print(out)
out.flat = [u+v for (u,v) in b]
out

(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [ ]:
print(x)
print(y)
x+y

[[1]
 [2]
 [3]]
[4 5 6]


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_broadcast_to.htm
a = np.arange(4).reshape(1,4)
a

array([[0, 1, 2, 3]])

In [ ]:
print(np.broadcast_to(a,(4,4)))

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_expand_dims.htm
x = np.array(([1,2],[3,4]))
print(x)
print(x.ndim)
x.shape

[[1 2]
 [3 4]]
2


(2, 2)

In [ ]:
x = np.array([(1,2),(3,4)])
x

array([[1, 2],
       [3, 4]])

In [ ]:
x = np.array([(1,2,3),(4,5)])
print(x)
x.shape

[(1, 2, 3) (4, 5)]


<ipython-input-29-f475ed4448e5>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([(1,2,3),(4,5)])


(2,)

In [ ]:
y = np.expand_dims(x, axis = 0)
print(y)
print(y.ndim)
y.shape

[[[1 2]
  [3 4]]]
3


(1, 2, 2)

In [ ]:
y = np.expand_dims(x, axis = 1)
print(y)
print(y.ndim)
y.shape

[[[1 2]]

 [[3 4]]]
3


(2, 1, 2)

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_squeeze.htm
x = np.arange(9).reshape(1,3,3)
print(x)
print(x.ndim)
x.shape

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
3


(1, 3, 3)

In [ ]:
y = np.squeeze(x)
print(y)
print(y.ndim)
y.shape

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


(3, 3)

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_concatenate.htm
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
b = np.array([[5,6],[7,8]])
print(b)
print(b.shape)

[[5 6]
 [7 8]]
(2, 2)


In [ ]:
c = np.concatenate((a,b))
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [ ]:
d = np.concatenate((a,b),axis = 1)
print(d)
print(d.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_stack.htm
c = np.stack((a,b),0)
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
d = np.stack((a,b),1)
print(d)
print(d.shape)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


In [ ]:
e = np.stack((a,b),2)
print(e)
print(e.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_hstack.htm
c = np.hstack((a,b))
print(c)
print(c.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_vstack.htm
d = np.vstack((a,b))
print(d)
print(d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_split.htm
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8]


In [ ]:
b = np.split(a,3)
print(b)
print(b[0])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]


In [ ]:
type(b)

list

In [ ]:
type(b[0])

numpy.ndarray

In [ ]:
a = np.arange(27)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
b = np.split(a,3)
print(b)
print(b[0])

[array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15, 16, 17]), array([18, 19, 20, 21, 22, 23, 24, 25, 26])]
[0 1 2 3 4 5 6 7 8]


In [ ]:
b = np.split(a,[4,7])
print(b)
print(b[1])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26])]
[4 5 6]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_hsplit.htm
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
b = np.hsplit(a,2)
print(b)
b[0]

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_vsplit.htm
c = np.vsplit(a,2)
print(c)
c[0]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_resize.htm
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
b = np.resize(a, (3,2))
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
b = np.resize(a,(3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_append.htm
b = np.append(a, [7,8,9])
print(b)
print(b.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [ ]:
c = np.append(a, [[7,8,9]],axis = 0)
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
d = np.append(a, [[5,5,5],[7,8,9]],axis = 1)
print(d)
print(d.shape)

[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
(2, 6)


In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_insert.htm
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
a

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = np.insert(a,3,[11,12])
b

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [ ]:
c = np.insert(a,1,[11],axis = 0)
c

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [ ]:
d = np.insert(a,1,11,axis = 1)
d

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_delete.htm
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.delete(a,1,axis = 1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.delete(a, np.s_[::2])

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
np.delete(a, np.s_[::2])

array([ 2,  4,  6,  8, 10])

In [ ]:
np.array([0, 1, 2, 3, 4])[np.s_[::2]]

array([0, 2, 4])

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_unique.htm
a = np.array([5,2,6,2,7,5,6,8,2,9])
a

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [ ]:
u = np.unique(a)
u

array([2, 5, 6, 7, 8, 9])

In [ ]:
u,indices = np.unique(a, return_index = True)
u

array([2, 5, 6, 7, 8, 9])

In [ ]:
indices

array([1, 0, 2, 4, 7, 9])

In [ ]:
#array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])
u,indices = np.unique(a,return_inverse = True)
u

array([2, 5, 6, 7, 8, 9])

In [ ]:
indices

array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5])

In [ ]:
u[indices]

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [ ]:
u,indices = np.unique(a,return_counts = True)
u

array([2, 5, 6, 7, 8, 9])

In [ ]:
indices

array([3, 2, 2, 1, 1, 1])