<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.17%20np_byte_swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_byte_swapping.htm
import numpy as np
a = np.array([1, 256, 8755], dtype=np.uint16)
a

array([   1,  256, 8755], dtype=uint16)

In [ ]:
print(a)
print([hex(i) for i in a])
[bin(i) for i in a]

[   1  256 8755]
['0x1', '0x100', '0x2233']


['0b1', '0b100000000', '0b10001000110011']

In [ ]:
print(a.byteswap(True))
print([hex(i) for i in a])
[bin(i) for i in a]

[   1  256 8755]
['0x1', '0x100', '0x2233']


['0b1', '0b100000000', '0b10001000110011']

In [ ]:
a = np.array([1, 256, 8755], dtype=np.uint16)
print(a)
print([np.binary_repr(i, width = 16) for i in a])
print(a.byteswap(True))
print([np.binary_repr(i, width = 16) for i in a])

[   1  256 8755]
['0000000000000001', '0000000100000000', '0010001000110011']
[  256     1 13090]
['0000000100000000', '0000000000000001', '0011001100100010']
