<a href="https://colab.research.google.com/github/KhantPhyo/CoLab_For-MachineLearning/blob/main/A.1.15%20np_statistical_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [ ]:
np.amin(a)

2

In [ ]:
np.amin(a,1) #row by row

array([3, 3, 2])

In [ ]:
np.amin(a,0) #col by col

array([2, 4, 3])

In [ ]:
np.amax(a)

9

In [ ]:
np.amax(a, axis = 0) # col by col

array([8, 7, 9])

In [ ]:
np.amax(a, axis = 1) # row by row

array([7, 8, 9])

In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.ptp.html
np.ptp(a)

7

In [ ]:
#numpy.ptp(a, axis=None, out=None, keepdims=<no value>)
np.ptp(a, axis = 1) # row by row

array([4, 5, 7])

In [ ]:
np.ptp(a, axis = 0) # col by col

array([6, 3, 6])

In [ ]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [ ]:
#numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)
np.percentile(a,50)

50.0

In [ ]:
np.percentile(a,50, axis = 1) #row by row

array([40., 20., 60.])

In [ ]:
np.percentile(a,50, axis = 0) #col by col

array([50., 40., 60.])

In [ ]:
np.median(a)

50.0

In [ ]:
np.median(a, axis = 0)

array([50., 40., 60.])

In [ ]:
np.median(a, axis = 1)

array([40., 20., 60.])

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
np.mean(a) #balance point

3.6666666666666665

In [ ]:
np.median(a) #center point

4.0

In [ ]:
8/3, 11/3, 14/3

(2.6666666666666665, 3.6666666666666665, 4.666666666666667)

In [ ]:
np.mean(a, axis = 0) # col by col, balance point

array([2.66666667, 3.66666667, 4.66666667])

In [ ]:
np.median(a, axis = 0)  # col by col, center point

array([3., 4., 5.])

In [ ]:
np.mean(a, axis = 1)

array([2., 4., 5.])

In [ ]:
np.median(a, axis = 1)

array([2., 4., 5.])

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
np.average(a)

2.5

In [ ]:
np.mean(a)

2.5

In [ ]:
wts = np.array([4,3,2,1])
wts

array([4, 3, 2, 1])

In [ ]:
np.average(a,weights = wts)

2.0

In [ ]:
np.average([1,2,3, 4],weights = [4,3,2,1], returned = True)

(2.0, 10.0)

In [ ]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
wt = np.array([3,5])
wt

array([3, 5])

In [ ]:
np.average(a, axis = 1, weights = wt)

array([0.625, 2.625, 4.625])

In [ ]:
np.average(a, axis = 1, weights = wt, returned = True)

(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))

In [ ]:
np.std([1,2,3,4])

1.118033988749895

In [ ]:
np.var([1,2,3,4])

1.25